# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request

name: "Continuous Integration"

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: sergioisidoro/github-transifex-action
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build Docker image"
        run: $(which docker) build --tag ${DOCKER_IMAGE}:latest .

      - name: "Run Docker image"
        run: $(which docker) run
          --interactive --rm
          --env-file docker-test.env --env TX_TOKEN=$TX_TOKEN
          --workdir=/app
          --volume ${GITHUB_WORKSPACE}:/app
          ${DOCKER_IMAGE}:latest
